title: tasha simone | designer
author: tasha simone
email: tashaspeterson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  bing bang pow action ladies and gents. your kinda queit, definitely feminist, 
  vegan, jesus-loving web developing superwoman is here and ready to party because it's almost 3am.

# social links
twitter_username: t_shasimone
github_username:  tashasimone

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
